### ISSUE TITLE
请问批量下载有考虑支持自定义范围文章下载吗

### ISSUE THREAD

**Issue by pyronn** [jooooock/wechat-article-exporter#10]
现在批量下载应该是会下载全部已加载的文章，不知道有没有考虑支持自定义范围的文章批量下载，比如最近的n篇，当前页的或者指定时间范围的文章，或者多选框可以自己选择。因为有时候并不想要下载全部的文章，有次翻了太多页，点了批量下载，快一千篇文章，也暂停不了。另外自定义范围的话感觉应该也能缓解一点流量的问题。

**Comment by jooooock** [comment]
感谢提出的建议！

其实我是有计划做一个列表视图的(类似表格)，当前的卡片视图比较占用空间。

做成列表视图的话，每一行就是一篇文章，包含标题，发布时间，摘要等一些基本的信息，也方便勾选，然后再配合顶部做一个过滤器就可以实现自定义范围过滤了。

**Comment by jooooock** [comment]
试试新版UI中的数据导出，可以自定义范围下载了
