### ISSUE TITLE
关于评论、阅读量、转发量等数据的导出

### ISSUE THREAD

**Issue by jooooock** [jooooock/wechat-article-exporter#11]
这些数据都是需要微信用户的登录信息才能抓取到的，最近试了一下 mitmproxy 代理工具，在这里记录一下抓取这些数据的方法。

下面这张图是带了`wap_sid2`和`pass_ticket`这两个 cookie 之后返回的文章 html 内容，可以看到已经渲染出了阅读数：
![image](https://github.com/user-attachments/assets/e0cc7416-eda4-4286-9ac6-1c9d4fb7ffa9)

下面这张图是通过接口抓取的评论数据，需要通过代理工具获取到`key`和`pass_ticket`这两个信息：
![image](https://github.com/user-attachments/assets/13c81fd7-a9b6-435a-b7d4-0459f5c78f7f)

**Comment by jooooock** [comment]
如果需要抓取这些数据的话，可以按照教程手动抓取这些用户信息，然后在导出文章的时候填入这些数据即可导出评论和阅读量、转发量、点赞量等数据了。

经初步测试，这些用户信息在同一个公众号中是不变的，不需要每篇文章都去抓取这些信息。

**Comment by hrbagang** [comment]
> 如果需要抓取这些数据的话，可以按照教程手动抓取这些用户信息，然后在导出文章的时候填入这些数据即可导出评论和阅读量、转发量、点赞量等数据了。
> 
> 经初步测试，这些用户信息在同一个公众号中是不变的，不需要每篇文章都去抓取这些信息。

手动抓取用户信息的教程，可以分享一下吗？谢谢！

**Comment by jooooock** [comment]
> > 如果需要抓取这些数据的话，可以按照教程手动抓取这些用户信息，然后在导出文章的时候填入这些数据即可导出评论和阅读量、转发量、点赞量等数据了。
> > 经初步测试，这些用户信息在同一个公众号中是不变的，不需要每篇文章都去抓取这些信息。
> 
> 手动抓取用户信息的教程，可以分享一下吗？谢谢！

这部分功能只是验证过，还没有开始做

**Comment by jooooock** [comment]
@hrbagang 
可以看下这个文档 https://github.com/jooooock/wechat-article-exporter/blob/master/docs/credentials.md
