### ISSUE TITLE
导出文件希望支持 日期以及 markdown格式

### ISSUE THREAD

**Issue by zh4n7wm** [jooooock/wechat-article-exporter#13]
- 导出的 html 中没有 `发布日期`，但列表页面中有的
- 导出格式能支持 `markdown` 就完美了，我目前是希望将公众号文章导出之后，放到 `vitepress` 中

**Comment by jooooock** [comment]
html中增加了发布时间和ip属地

**Comment by zh4n7wm** [comment]
感谢支持

**Comment by jooooock** [comment]
格式问题参考 #18

**Comment by zh4n7wm** [comment]
好的，谢谢！

我现在通过 `html2md -i index.html > index.md` 来转换的，效果只能说将就吧
