### ISSUE TITLE
建议可以整合批量下载转换成矢量 pdf 的功能

### ISSUE THREAD

**Issue by colin4k** [jooooock/wechat-article-exporter#15]
目前我是手动处理，解压批量导出的 zip文件，创建文章文件链接清单文件，然后用我魔改过的wechat-article-dl 工具再批量创建矢量 pdf 文件，最后再用 adobe pdf 合并成一个 pdf 文件，可参考：
https://github.com/colin4k/wechat-article-dl

**Comment by jooooock** [comment]
#18
