### ISSUE TITLE
能不能对数据导出界面的列表直接单独导出呀，不需要导出所有文章zip，仅导出公众号历史文章列表即可

### ISSUE THREAD

**Issue by ALifeGuide** [jooooock/wechat-article-exporter#19]
![Uploading 截图_20241011171253.png…]()
目前的列表全选粘贴到excel中有一些问题：
①文章标题过长时会显示不全，以省略号代替
②原文链接不显示
③格式有些错乱
所以想问问大大，数据导出界面的文章列表后续会支持列表单独导出excel表格么

**Comment by jooooock** [comment]
你上传的图片没传完整

另外，想问下你导出这个数据的场景是什么样的？后续怎么使用这个数据？
