### ISSUE TITLE
下载失败问题

### ISSUE THREAD

**Issue by pprp** [jooooock/wechat-article-exporter#2]
在选择批量下载以后，等到加载到最后一个文章的时候会卡主，导致下载失败
<img width="247" alt="image" src="https://github.com/user-attachments/assets/4eff4fc9-0f18-49e7-a880-10fd251a0894">

**Comment by jooooock** [comment]
控制台有没有报错信息

**Comment by pprp** [comment]
<img width="768" alt="image" src="https://github.com/user-attachments/assets/d1d640c1-125c-42de-8767-80720cc2b861">

又进行了几次测试，发现如果缓存过多会卡主，缓存少的情况下 < 100 的时候没有问题

**Comment by jooooock** [comment]
出现 **下载失败，请重试** 这个错误是因为抓取html内容失败，有可能是抓取频率太高的原因

**Comment by jooooock** [comment]
我把批量下载的间隔调成2秒了，之前是200毫秒，并且所有人用的是同一个ip去微信请求的，所以太频繁的话应该很容易被检测

**Comment by pprp** [comment]
能否设置当抓取失败以后，停止抓取，将已有内容保存下来? 未抓取内容舍弃

**Comment by jooooock** [comment]
也可以，根据你那个截图，如果出现失败，大概率后面的请求也会失败

**Comment by pprp** [comment]
感谢 @jooooock  ，我这里已经测试可以正常下载了
