### ISSUE TITLE
关于公众号数据导出想要新加的需求TAT

### ISSUE THREAD

**Issue by Stars0w0** [jooooock/wechat-article-exporter#20]
我看了好像主要是对文章进行下载TAT但是其实网上找了很多目的都有点偏移我的需求，是想要获取的是自己公众号内部的所有推文的数据，然后因为时间跨度大概差不多有10年，导致很多付费的费用会爆炸，免费的似乎又有导出限制或者是导出的并没有包括阅读数量

**Comment by jooooock** [comment]
阅读量的导出需要用到微信用户信息，这个需要手动抓取cookie才行(有一定的使用门槛)，可以参考 #11 ，目前验证过是可以抓的，但是不确定能不能批量抓到这些数据
