### ISSUE TITLE
使用中发现了一个小问题（未完整加载，但显示全部加载完毕），麻烦帮忙确认一下，谢谢。

### ISSUE THREAD

**Issue by elvis-bigdog** [jooooock/wechat-article-exporter#24]
使用自己的公众号可以缓存希望查询公众号的文章，但是不知道是不是有什么限制，在缓存的时候右下角出现“加载进度: 35/108”，但是在正中间出现“已全部加载完毕”的显示，通过手机上个人公众号查询中，是可以看到更多文章的，能否帮忙确认一下是什么原因导致的问题？
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/b4fa77d8-957d-4be3-8785-b167f45d7c4b">

**Comment by jooooock** [comment]
公众号名字发一下

**Comment by elvis-bigdog** [comment]
> 公众号名字发一下

某男舒立

**Comment by luzhiyuan787** [comment]
我这发现一个问题，应该也算未加载完整。
就是通过手机查看到的公众号的某一篇文章，但用wechat-article-exporter在加载时没有加载出来。

复现和截图：
- 1、公众号：河北省教育考试院
- 2、有问题的文章名称：“权威 科学 公益 便捷 河北省高考志愿填报智能参考系统全面优化升级”
- 3、截图:
![image](https://github.com/user-attachments/assets/448dd3a1-3bf4-4bfd-ac1f-c7b050cc765c)
如上图所示，2024年整个5月份都没有文章；但通过手机查看公众号是有的，如下图所示
![image](https://github.com/user-attachments/assets/c0cac82b-2ce5-461e-aa51-c57dc1326c0a)

**Comment by jooooock** [comment]
> 麻烦也帮忙确认下，谢谢~

这个问题已复现，应该是由于begin参数计算错误导致的某些文章被跳过了
@luzhiyuan787

**Comment by luzhiyuan787** [comment]
> @elvis-bigdog @luzhiyuan787 问题已修复，但是浏览器本地缓存的数据有问题，需要清空之后重新拉取文章列表数据。清空缓存数据的方法参考 [数据清理](https://github.com/jooooock/wrx?tab=readme-ov-file#%E6%95%B0%E6%8D%AE%E6%B8%85%E7%90%86), 第二步不是**wrx**而是**wechat-article-exporter**

好的，感谢～

**Comment by elvis-bigdog** [comment]
> @elvis-bigdog @luzhiyuan787 问题已修复，但是浏览器本地缓存的数据有问题，需要清空之后重新拉取文章列表数据。清空缓存数据的方法参考 [数据清理](https://github.com/jooooock/wrx?tab=readme-ov-file#%E6%95%B0%E6%8D%AE%E6%B8%85%E7%90%86), 第二步不是**wrx**而是**wechat-article-exporter**

感谢大佬~
