### ISSUE TITLE
通过biz搜索的结果，显示个人，无法显示原公众号的名称

### ISSUE THREAD

**Issue by Hatcat123** [jooooock/wechat-article-exporter#26]
输入 MzU1MDcwNjAxMQ==
显示个人
![image](https://github.com/user-attachments/assets/3681c30d-6f9e-41fe-b513-0d3d51d4a06e)
此时文章页面显示个人
![image](https://github.com/user-attachments/assets/85008c3e-81f1-4617-ba8d-80a460e67bd6)
数据导出也是个人

**Comment by jooooock** [comment]
biz搜索的逻辑调整了，具体可以看下这个#31
