### ISSUE TITLE
火绒报病毒

### ISSUE THREAD

**Issue by hrbagang** [jooooock/wechat-article-exporter#28]
详细log信息，参见附件文件
[360log.txt](https://github.com/user-attachments/files/17492147/360log.txt)

![image](https://github.com/user-attachments/assets/e4864963-eb5e-4f1e-ad84-61ab1ffa8892)

**Comment by hrbagang** [comment]
不好意思，杀毒软件的名称写错了，应该是火绒。

**Comment by jooooock** [comment]
能重现吗？是下载那篇文章的时候报的

**Comment by hrbagang** [comment]
> 能重现吗？是下载哪篇文章的时候报的

家里电脑，等晚些时候再试试

**Comment by leangjia** [comment]
本人最新版本的火绒V5.0.76.1，未见报毒。

**Comment by jooooock** [comment]
无法重现
