### ISSUE TITLE
大佬，一个公众号爬多了会不会被禁掉啊

### ISSUE THREAD

**Issue by Xsir0** [jooooock/wechat-article-exporter#30]
大佬，一个公众号爬多了会不会被禁掉啊

**Comment by jooooock** [comment]
整个过程主要分两部分：
第一部分是利用你注册的公众号去微信公众号后台拉取文章数据，拉取完之后会保存在浏览器本地缓存中(只是存了文章链接和一些元数据，文章内容并没有缓存)
第二部分，就是从浏览器缓存把数据导出(批量下载文章)，这部分主要是从缓存中获取文章链接，并下载整个文章的资源

目前测试过程中，第一步短时间内爬取超过600条左右文章数据，会被微信封一段时间(一般是几个小时，最多24小时)，只是封掉获取文章列表这个接口，对公众号其他功能好像没啥印象，甚至对搜索接口都不影响。
第二部分下载，目前没有出现被封的情况。
