### ISSUE TITLE
大佬下载文章失败呢，辛苦看一下。

### ISSUE THREAD

**Issue by Beihaiyumao** [jooooock/wechat-article-exporter#34]
大佬下载文章失败呢，辛苦看一下，下载下来都是22b的空压缩包。感觉应该是代理挂了
https://vproxy-01.jooooock.workers.dev
https://vproxy-02.jooooock.workers.dev

**Comment by jooooock** [comment]
我这里没有复现，你直接访问这两个地址访问不了嘛

**Comment by leangjia** [comment]
我也碰到打包下回来都是22b的空包，前提是按时间选择下载时，可重现。

**Comment by leangjia** [comment]
@jooooock @Beihaiyumao

**Comment by jooooock** [comment]
请提供重新步骤 @leangjia
