### ISSUE TITLE
token 已过期是什么情况呢？

### ISSUE THREAD

**Issue by asiyoua** [jooooock/wechat-article-exporter#39]
![CleanShot 2024-11-21 at 10 34 49@2x](https://github.com/user-attachments/assets/b7848325-cbed-42ec-87dc-5a17df1accb3)

**Comment by asiyoua** [comment]
而且我打不开微信二维码
![CleanShot 2024-11-21 at 10 35 36@2x](https://github.com/user-attachments/assets/5d398675-b0f6-46b4-85e0-3f358d610844)

**Comment by jooooock** [comment]
打开网络面板，看一下获取二维码的请求

**Comment by jooooock** [comment]
token已过期的话，需要重新扫码登陆
二维码不显示的问题，确认下是否开启了https
