### ISSUE TITLE
设置中的下载选项没有保存的按钮，阅读量无法下载

### ISSUE THREAD

**Issue by WuJinfeng0715** [jooooock/wechat-article-exporter#51]
已设置好Credentials。设置中的下载选项在选择后没有保存按钮，请问如何操作？谢谢

![image](https://github.com/user-attachments/assets/9850fc5a-e346-4993-93ec-9218dc224736)

**Comment by WuJinfeng0715** [comment]
更新：在设置好Credentials的情况下，下载的html文件包含评论。但没有阅读量和点赞量。

**Comment by jooooock** [comment]
> 设置中的下载选项在选择后没有保存按钮

下载选项目前还处于内测阶段，还不能用

> 但没有阅读量和点赞量。

你下载的是哪篇文章？

**Comment by WuJinfeng0715** [comment]
> 你下载的是哪篇文章？

感谢回复。所有文章在打包后都没有点赞量和折叠的回复评论数据。请问点赞量也是保存在html文件中吗？比如这个链接：https://mp.weixin.qq.com/s?__biz=MzkzMTY2MzMzMQ==&mid=2247484588&idx=1&sn=88f1987a7807e913a5bf140640cd54e0&chksm=c319ef5b5c5417f92ce0d1b3d02f7ecac9e889e4240d57823b88981bb2ba0167595dfa59259d&scene=126&sessionid=1733280651#rd

**Comment by jooooock** [comment]
这是我刚下载的这篇文章的效果：

![image](https://github.com/user-attachments/assets/41bcc4a7-9461-4014-9570-9ae11b6490a3)


你是不是没有设置`wap_sid2`这个参数？这个是用于获取点赞量和阅读量的，上面那些是获取评论的

![image](https://github.com/user-attachments/assets/22f69900-0458-4ac6-8814-3914844df5cd)

折叠的评论还没有找到相关接口，所以这个目前获取不到。

**Comment by WuJinfeng0715** [comment]
非常感谢帮助，更新wap_sid2后，已解决问题。最后一个小问题，对于文章数目很多的公众号，在网页端，拉取缓存是否只能人工拉到最后一篇？是否有办法一键加载所有的缓存。

**Comment by jooooock** [comment]
目前只能手动一页一页加载，因为我担心做成自动化的话很容易超出微信的接口限制，被微信封掉。

**Comment by WuJinfeng0715** [comment]
> 目前只能手动一页一页加载，因为我担心做成自动化的话很容易超出微信的接口限制，被微信封掉。

非常感谢。我没有其他问题了。非常棒的项目！谢谢你提供的公共产品。
